sudo: false
language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
env:
  - DJANGO=1.8
  - DJANGO=1.9
  - DJANGO=master
matrix:
  exclude:
    - python: "3.3"
      env: DJANGO=1.9
    - python: "3.3"
      env: DJANGO=master
  allow_failures:
    - python: "2.7"
      env: DJANGO=master
    - python: "3.4"
      env: DJANGO=master
    - python: "3.5"
      env: DJANGO=master
install:
  - pip install tox
script:
  - tox -e py${TRAVIS_PYTHON_VERSION//[.]/}-$DJANGO